Repository MicrosoftDocs/cpp-docs.ja-jp, pull requests merged in 2019-11, with the labels that each got.

#173 fopen,_wfopen と fopen_s,_wfopen_s ページの記述の修正
  docs/c-runtime-library/reference/fopen-s-wfopen-s.md
  docs/c-runtime-library/reference/fopen-wfopen.md
Labels: In Progress, Linguistic Suggestion, Technical Issue

#176 [LOC]Fix "'条件演算子: @no__t 0:'"→"'条件演算子: &quest; :'"
  docs/cpp/conditional-operator-q.md
Labels: In Progress

#177 Visual StudioC++での C/ → Visual Studio での C/C++
  docs/build/projects-and-build-systems-cpp.md
Labels: Accepted, Linguistic Suggestion

#178 visual studio → Visual Studio
  docs/build/projects-and-build-systems-cpp.md
Labels: In Progress

#179 "署名" -> "signed"
  docs/cpp/data-type-ranges.md
Labels: In Progress

#180 C++asp.net → C++コンパイル
  docs/build/projects-and-build-systems-cpp.md
Labels: In Progress
