Repository MicrosoftDocs/cpp-docs.ja-jp, pull requests merged in 2019-12, with the labels that each got.

#184 X64 → x64
  docs/build/projects-and-build-systems-cpp.md
Labels: Accepted

#186 OC]Back-Translation "<新しい>演算子"→"<new> 演算子"
  docs/standard-library/new-operators.md
Labels: Accepted

#182 #directives → #ディレクティブ
  docs/build/projects-and-build-systems-cpp.md
Labels: Accepted, Linguistic Suggestion

#181 プリC++プロセッサ → C++プリプロセッサ
  docs/build/projects-and-build-systems-cpp.md
Labels: Accepted, Linguistic Suggestion

#183 コンパイラC++ → C++コンパイラ
  docs/build/projects-and-build-systems-cpp.md
Labels: Accepted, Linguistic Suggestion

#188 Improve awkward translation
  docs/build/projects-and-build-systems-cpp.md
Labels: Accepted, Linguistic Suggestion

#185 [LOC]fixed inappropriate japanese "**new**オペレーター"→"**new** 演算子"
  docs/cpp/new-operator-cpp.md
Labels: In Progress, Linguistic Suggestion

#190 Move `C++` to the correct position
  docs/build/projects-and-build-systems-cpp.md
Labels: Accepted, Linguistic Suggestion

#189 [LOC]fixed inappropriate japanese "new (新規スロット vtable の)"→"new (vtabl…
  docs/cpp/new-operator-cpp.md
Labels: Accepted, Linguistic Suggestion

#191 Improve awkward translation
  docs/build/projects-and-build-systems-cpp.md
Labels: Accepted, Linguistic Suggestion

#192 Correct broken translation
  docs/build/projects-and-build-systems-cpp.md
Labels: Accepted, Linguistic Suggestion

#195 Cmake プロジェクト → CMake プロジェクト
  docs/build/projects-and-build-systems-cpp.md
Labels: Accepted

#194 Visual studio → Visual Studio
  docs/build/creating-and-managing-visual-cpp-projects.md
Labels: Accepted

#193 visual studio 2017 → Visual Studio 2017
  docs/build/creating-and-managing-visual-cpp-projects.md
Labels: Accepted, Linguistic Suggestion

#199 Visual studio で Cmake → Visual Studio で CMake
  docs/build/creating-and-managing-visual-cpp-projects.md
Labels: Accepted

#201 `ビジュアルC++` → ` Visual C++`
  docs/build/working-with-project-properties.md
Labels: Accepted

#200 `_projectname_` > `_プロジェクト名_ `
  docs/build/working-with-project-properties.md
Labels: Accepted, Linguistic Suggestion

#203 `プロパティページC++()` → `プロパティページ(C++)`
  docs/build/working-with-project-properties.md
Labels: Accepted
