Repository MicrosoftDocs/cpp-docs.ja-jp, pull requests merged in 2019-09, with the labels that each got.

#122 [LOC] Back-Translation "場所句"→"WHERE句"
  docs/data/odbc/recordset-performing-a-join-odbc.md
Labels: Accepted

#120 Typo "_ _except"→"__except"
  docs/error-messages/compiler-errors-2/compiler-error-c2702.md
Labels: Accepted, Linguistic Suggestion

#119 fixed inappropriate japanese
  docs/error-messages/compiler-errors-2/compiler-error-c2701.md
Labels: Accepted, Linguistic Suggestion

#110 [LOC] Back-Translation "削除演算子"→"delete 演算子"
  docs/cpp/new-and-delete-operators.md
Labels: Accepted, Linguistic Suggestion

#118 fixed inappropriate japanese
  docs/error-messages/compiler-errors-2/compiler-error-c2706.md
Labels: Accepted, Linguistic Suggestion

#121 Typo "_ _finally"→"__finally"
  docs/error-messages/compiler-errors-1/compiler-error-c2494.md
Labels: Linguistic Suggestion, Partially Accepted, Source Issue

#123 Typo "_ _except"→"__except"
  docs/c-runtime-library/reference/malloca.md
Labels: Accepted

#128 Typo "*_ _identifier*"→"*__identifier*"
  docs/error-messages/compiler-warnings/compiler-warnings-c4200-through-c4399.md
Labels: Accepted

#127 Typo "_ _try"→"__try"
  docs/build/reference/eh-exception-handling-model.md
Labels: Accepted

#126 Typo "_ _except"→"__except"
  docs/error-messages/compiler-errors-2/compiler-errors-c2700-through-c2799.md
Labels: Accepted

#125 Typo "_ _except"→"__except"
  docs/c-runtime-library/reference/alloca.md
Labels: Accepted

#130 Typo "_ _finally"→"__finally"
  docs/dotnet/basic-concepts-in-using-managed-exceptions.md
Labels: Accepted

#135 [LOC] Back-Translation "COccManager:: Splitのテンプレート"→"COccManager::Spl…
  docs/mfc/reference/coccmanager-class.md
Labels: Accepted

#133 [LOC] Back-Translation "**お試しください**と**キャッチ**"→"**try**と**catch**"
  docs/cpp/how-to-interface-between-exceptional-and-non-exceptional-code.md
Labels: Accepted, Linguistic Suggestion

#132 fix "[方法: 例外的なコードと非例外的なコードをインターフェイスで連結する]"→"[方法: 例外的なコードと非例外的なコード間のイン…
  docs/cpp/how-to-design-for-exception-safety.md
Labels: Accepted, Linguistic Suggestion

#136 Typo "__Except"→"__except"
  docs/cpp/try-except-statement.md
Labels: Accepted

#131 [LOC] Back-Translation "使われて"→"CObList::CObList"
  docs/mfc/reference/cobject-class.md
Labels: Accepted, Linguistic Suggestion

#134 [LOC] Back-Translation "位置"→"POSITION"
  docs/mfc/reference/coblist-class.md
Labels: Accepted, Linguistic Suggestion

#138 [LOC] Back-Translation "場所"→"WHERE"
  docs/mfc/reference/cdaorecordset-class.md
Labels: Accepted, Technical Issue

#140 [LOC] Back-Translation "**新しい**演算子"→"**new**演算子"
  docs/cpp/expressions-with-unary-operators.md
Labels: Accepted

#139 [LOC] Back-Translation "**新しい**演算子"→"**new**演算子"
  docs/c-runtime-library/reference/query-new-mode.md
Labels: Accepted

#143 [LOC] Back-Translation "新しい演算子"→"new 演算子"
  docs/cpp/new-and-delete-operators.md
Labels: Accepted

#142 [LOC] Back-Translation "**キャッチ**"→"**catch**"
  docs/cpp/how-catch-blocks-are-evaluated-cpp.md
Labels: Accepted

#144 [LOC] Back-Translation "新しいと削除演算子"→"new および delete 演算子"
  docs/cpp/general-rules-for-operator-overloading.md
Labels: Accepted

#150 C++ 言語リファレンス、加法演算子 ページの記載の更新
  docs/cpp/additive-operators-plus-and.md
Labels: Linguistic Suggestion, Partially Accepted, Source Issue

#153 C++ 言語リファレンス、抽象クラス (C++) ページの記載の更新
  docs/cpp/abstract-classes-cpp.md
Labels: Linguistic Suggestion, Partially Accepted, Source Issue

#154 [LOC] Fixed inappropriate japanese "できれ"→"CATCH"
  docs/mfc/reference/exception-processing.md
Labels: Accepted, Linguistic Suggestion

#146 起動と終了 (C++) ページ
  docs/cpp/startup-and-termination-cpp.md
Labels: Accepted, Linguistic Suggestion

#147 C++ 言語リファレンスの abort 関数の記述を修正
  docs/cpp/abort-function.md
Labels: Accepted, Linguistic Suggestion

#148 C++ 言語リファレンス、起動に関するその他の考慮事項ページの記載の更新
  docs/cpp/additional-startup-considerations.md
Labels: Accepted, Linguistic Suggestion

#149 C++ 言語リファレンス、終了に関するその他の考慮事項ページの記載の更新
  docs/cpp/additional-termination-considerations.md
Labels: Accepted, Linguistic Suggestion

#151 C++ 言語リファレンス、アルゴリズム (現代的なC++) ページの記載の更新
  docs/cpp/algorithms-modern-cpp.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#156 [LOC] Fixed inappropriate japanese "AfxThrowDBException"
  docs/mfc/reference/exception-processing.md
Labels: Accepted, Linguistic Suggestion

#152 C++ 言語リファレンス、アドレス演算子: & ページの記載の更新
  docs/cpp/address-of-operator-amp.md
Labels: Linguistic Suggestion, Partially Accepted, Source Issue

#155 C++ 言語リファレンス、エイリアス と typedef (C++) ページの記載の更新
  docs/cpp/aliases-and-typedefs-cpp.md
Labels: Linguistic Suggestion, Partially Accepted, Source Issue

#158 Update vscpp-step-0-installation.md
  docs/build/vscpp-step-0-installation.md
Labels: Accepted, Linguistic Suggestion

#157 Update vscpp-step-1-create.md
  docs/build/vscpp-step-1-create.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#159 Update vscpp-step-2-build.md
  docs/build/vscpp-step-2-build.md
Labels: Accepted, Linguistic Suggestion
