Repository MicrosoftDocs/cpp-docs.ja-jp, pull requests merged in 2020-01, with the labels that each got.

#210 Fix broken translation
  docs/build/working-with-project-properties.md
Labels: Accepted, Technical Issue

#202 `MSVC Compiler options` → `MSVC コンパイラ オプション`
  docs/build/working-with-project-properties.md
Labels: Accepted, Linguistic Suggestion

#211 Fix broken translation
  docs/build/create-reusable-property-configurations.md
Labels: Accepted, Linguistic Suggestion

#212 correct case
  docs/build/create-reusable-property-configurations.md
Labels: Accepted

#213 correct case
  docs/build/project-property-inheritance.md
Labels: Accepted

#214 Fix broken translation
  docs/build/create-reusable-property-configurations.md
Labels: Accepted, Linguistic Suggestion

#209 Modifying the scope of a link
  docs/build/working-with-project-properties.md
Labels: Accepted, Linguistic Suggestion

#204 [LOC]Back-Translation "[プライベート]"→"[private]"
  docs/cpp/public-cpp.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#206 [LOC]Back-Translation "[仮想]"→"[virtual]"
  docs/cpp/struct-cpp.md
Labels: Accepted, Linguistic Suggestion

#205 [LOC]Back-Translation "[保護]"→"[protected]"
  docs/cpp/member-access-control-cpp.md
Labels: Accepted, Linguistic Suggestion

#207 [LOC]Back-Translation "[仮想]"→"[virtual]"
  docs/cpp/class-cpp.md
Labels: Accepted, Linguistic Suggestion

#208 Improve awkward translation
  docs/build/working-with-project-properties.md
Labels: Accepted, Linguistic Suggestion

#216 Fix "nonedit"
  docs/mfc/reference/cdataexchange-class.md
Labels: Accepted, Linguistic Suggestion

#217 `visual studio` -> `Visual Studio`
  docs/build/clang-support-msbuild.md
Labels: Accepted

#218 `clang` -> `Clang`
  docs/build/clang-support-msbuild.md
Labels: Accepted

#223 Improve awkward translation
  docs/build/how-to-organize-project-output-files-for-builds.md
Labels: Accepted, Linguistic Suggestion
